import streamlit as st
import pandas as pd
import pdfplumber
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# --- 1. PAGE CONFIG & STYLING ---
st.set_page_config(page_title="AI Resume ATS", layout="wide")
st.title("📄 AI Resume Scanner & ATS Optimizer")

# --- 2. THE LOGIC (Functions) ---
def clean_text(text):
    text = re.sub(r'http\S+\s*', ' ', str(text))
    text = re.sub(r'[^\w\s]', ' ', text)
    return text.lower().strip()

# --- 3. SIDEBAR INPUTS ---
with st.sidebar:
    st.header("Upload Center")
    uploaded_file = st.file_uploader("Upload Resume (PDF)", type="pdf")
    jd_text = st.text_area("Paste Job Description", height=200)

# --- 4. MAIN APP LOGIC ---
if uploaded_file is not None:
    # STEP A: Extract Text
    with pdfplumber.open(uploaded_file) as pdf:
        resume_text = ""
        for page in pdf.pages:
            resume_text += page.extract_text()
    
    # STEP B: Initialize Variables (The "Safety" step to avoid NameError)
    match_score = 0
    category = "General Professional" # Default if ML fails
    
    # STEP C: Matching Logic (Only if JD is provided)
    if jd_text:
        clean_resume = clean_text(resume_text)
        clean_jd = clean_text(jd_text)
        
        vectorizer = TfidfVectorizer(stop_words='english')
        matrix = vectorizer.fit_transform([clean_jd, clean_resume])
        match_score = round(cosine_similarity(matrix[0:1], matrix[1:2])[0][0] * 100, 2)
        
        # Simple Logic to "Predict" Category based on Keywords (For Demo)
        if "python" in clean_resume or "data" in clean_resume:
            category = "Data Science / Analytics"
        elif "java" in clean_resume or "developer" in clean_resume:
            category = "Software Development"
        else:
            category = "Management / Administration"

    # --- 5. DISPLAY RESULTS ---
    col1, col2 = st.columns(2)
    with col1:
        st.metric("ATS Match Score", f"{match_score}%")
    with col2:
        st.metric("Predicted Role", category)

    # --- 6. THE DOWNLOAD REPORT (The Fix) ---
    # We define the string AFTER the variables match_score and category are created
    report_content = f"""
    AI RESUME ANALYSIS REPORT
    -------------------------
    Predicted Job Role: {category}
    ATS Match Score: {match_score}%
    
    Generated by: AI Resume Scanner (2026)
    """

    st.divider()
    st.download_button(
        label="📥 Download Analysis Report",
        data=report_content,
        file_name="Resume_Analysis.txt",
        mime="text/plain"
    )

else:
    st.info("Please upload a PDF to see the analysis and download your report.")
